### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by vdrover** [chacawaca/docker-post-recording#16]
Here is the docker compose I am using on Ubuntu 22. Posting for others who may be interested. Working great, and customizing comskip.ini was super easy.

Note that the ` LD_LIBRARY_PATH=/usr/local/lib/` environment variable was not needed on my system as reported for unraid. I also did not need UMASK.

 ```
  post-recording:
    container_name: post-recording
    image: chacawaca/post-recording
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - SOURCE_EXT=ts
      - CONVERSION_FORMAT=mkv
      - SUBTITLES=0
      - DELETE_TS=1 # 0 = Yes, 1 = No, 2 = Move to backup
      - POST_PROCESS=comchap # option are comchap or comcut. default: comchap
    volumes:
      - docker/appdata/postrecording:/config:rw
      - /mnt/dvr/postrecording_watch:/watch:rw
      - /mnt/dvr/postrecording_backup:/backup:rw
```
