### ISSUE TITLE
MKV files permissions are `0600`,  EDL files are `0644`

### ISSUE THREAD

**Issue by vdrover** [chacawaca/docker-post-recording#18]
This image is working well for me on Ubuntu 22. However, noticed a difference in permissions between output files. MKV are `0600` while EDL files are the expected `0644`. File ownership for each is as expected (UID=1000).

Here is my docker compose:
```
  post-recording:
    restart: always
    container_name: post-recording
    image: chacawaca/post-recording
    environment:
      - PUID=1000
      - PGID=1000
      - SOURCE_EXT=ts
      - CONVERSION_FORMAT=mkv
      - SUBTITLES=1 # Extract subtitles to .srt. 0= Yes, 1 = No
      - DELETE_TS=0 # 0 = Yes, 1 = No, 2 = Move to backup
      - POST_PROCESS=comchap # option are comchap or comcut. default: comchap
    volumes:
      - /appdata/postrecording:/config:rw
      - /mnt/emby:/watch:rw
```

Here is my custom.sh
```
#!/bin/bash

#----------------DONT MODIFY THIS PART----------------

date=$(date +"%d-%m-%Y-%H%M")
IFS=$(echo -en "\n\b")
export LD_LIBRARY_PATH=/usr/local/lib

INPUT="$1"
OUTPUT="$2"
INPUTSRT="$3"

LogFile=/config/log/ffmpeg/"$(basename "$INPUT" | sed 's/\.[^.]*$//')".$date.log


exec 3>&1 1>>${LogFile} 2>&1
mediainfo --Inform="Video;codec_name=%Format%" "$INPUT" | head -c 14 >> "$OUTPUT".txt
source "$OUTPUT".txt

#------------------MODIFY THIS PART-------------------
# crf 20 - up to 50% reduction
ffmpeg -i "$INPUT" -hide_banner -loglevel info -max_muxing_queue_size 512 -c:v libx265 -brand mp42 -crf 20 -ac 2 -c:a libfdk_aac -b:a 128k -ignore_unknown -map 0 "$OUTPUT"
#----------------DONT MODIFY THIS PART----------------

rm "$OUTPUT".txt
```
